### ISSUE TITLE
Closing windows application using windowManager.destroy() takes a lot more time when protocol_handler is included.

### ISSUE THREAD

**Issue by IvoB1987** [leanflutter/protocol_handler#16] opened 2024-03-21 11:44 UTC
I have a Flutter windows desktop application. And I use `window_manager` where I call `windowManager.destroy()` to close the application. The strange part is that when when I add `protocol_handler` to the pubspec file this closing takes some extra seconds in release builds. I don't even import `protocol_handler` in any of the dart files. I don't know if this is an error of `window_manager` or of `protocol_handler` but it seems weird that just the inclusion in the pubspec has impact on how the application behaves. Any idea why this is and if this needs fixing in this package? Here's a minimum reproducable example:

```
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: TextButton(
          child: const Text('Close'),
          onPressed: () => windowManager.destroy(),
        ),
      ),
    ));
  }
}
```

**Comment by lijy91** [comment] 2024-05-18 09:37
I tested it under flutter 3.19.6 and couldn't reproduce this problem.

**Comment by lijy91** [comment] 2024-05-18 09:40
Since I can't reproduce it, I'll close it first. If you have more specific reproduction conditions, please let me know.

**Closed by lijy91** 2024-05-18 09:40 UTC
